# Generated by Django 5.0.4 on 2024-05-04 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Айді')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
            ],
            options={
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name_plural': 'Зображення',
            },
        ),
        migrations.CreateModel(
            name='OfferColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_en', models.CharField(max_length=255, verbose_name='Колір англійською')),
                ('color_ua', models.CharField(max_length=255, verbose_name='Колір українською')),
                ('color_ru', models.CharField(max_length=255, verbose_name='Колір російською')),
            ],
            options={
                'verbose_name_plural': 'Кольори',
            },
        ),
        migrations.CreateModel(
            name='OfferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ua', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Типи товарів',
            },
        ),
        migrations.CreateModel(
            name='Parametr',
            fields=[
                ('parametr_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Параметр айді')),
                ('parametr_name', models.CharField(choices=[('Color', 'Цвет'), ('Size', 'Размер'), ('Article', 'Артикл'), ('Material', 'Матеріал'), ('Country of production', 'Країна виробника'), ('Description', 'Опис російською')], max_length=1000, verbose_name='Назва')),
                ('parametr_value', models.CharField(max_length=1000, verbose_name='Значення')),
            ],
            options={
                'verbose_name_plural': 'Параметри',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Офер айді')),
                ('model', models.CharField(max_length=1000, verbose_name='Модель')),
                ('size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL'), ('2XS', '2XS'), ('3XS', '3XS'), ('4XS', '4XS'), ('5XS', '5XS')], max_length=255, verbose_name='Розмір товару')),
                ('article', models.CharField(max_length=100, verbose_name='Артикл')),
                ('desc', models.TextField(verbose_name='Опис російською')),
                ('desc_ua', models.TextField(verbose_name='Опис українською')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('stock', models.IntegerField(verbose_name='Кількість')),
                ('enable', models.BooleanField(default=True, verbose_name='Статус')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.category', verbose_name='Категорія')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.offercolor', verbose_name='Колір')),
                ('offer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.offertype', verbose_name='Тип товару')),
            ],
            options={
                'verbose_name_plural': 'Товари',
            },
        ),
    ]
