# Generated by Django 5.0.4 on 2024-05-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offercolor',
            name='color_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Колір російською'),
        ),
    ]
