# Generated by Django 5.0.4 on 2024-04-30 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferSize',
            fields=[
                ('id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OfferType',
            fields=[
                ('id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name_ua', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='id',
        ),
        migrations.AddField(
            model_name='offer',
            name='model',
            field=models.CharField(default=1, max_length=1000, verbose_name='Модель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='name_ua',
            field=models.CharField(default=1, max_length=1000, verbose_name='Назва українською'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Офер айді'),
        ),
        migrations.AddField(
            model_name='offer',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.offersize'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.offertype'),
            preserve_default=False,
        ),
    ]
