# Generated by Django 5.0.4 on 2024-05-14 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametr',
            old_name='parametr_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='parametr',
            old_name='parametr_value',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.offertype', verbose_name='Тип товару'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XS', 'XS'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL'), ('2XS', '2XS'), ('3XS', '3XS'), ('4XS', '4XS'), ('5XS', '5XS')], max_length=255, verbose_name='Розмір товару'),
        ),
    ]
