# Generated by Django 5.0.4 on 2024-04-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_offersize_offertype_remove_offer_id_offer_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersize',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offertype',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
