# Generated by Django 5.0.4 on 2024-05-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_offercolor_color_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offercolor',
            name='color_en',
            field=models.CharField(max_length=255, unique=True, verbose_name='Колір англійською'),
        ),
    ]
