# Generated by Django 5.0.4 on 2024-05-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_offer_images_offer_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='offer',
            name='images',
            field=models.TextField(blank=True, null=True, verbose_name='Зображення'),
        ),
    ]
