# Generated by Django 5.0.4 on 2024-05-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_rename_parametr_name_parametr_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='parameters',
        ),
        migrations.DeleteModel(
            name='Parametr',
        ),
    ]
