# Generated by Django 5.0.4 on 2024-04-30 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_offersize_id_alter_offertype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.offertype', verbose_name='Тип товару'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.offersize', verbose_name='Розмір товару'),
        ),
    ]
