# Generated by Django 5.0.4 on 2024-05-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_remove_offer_images_delete_image_offer_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offertype',
            name='name_ru',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='offertype',
            name='name_ua',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
