# Generated by Django 5.0.4 on 2024-04-30 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_offer_offer_type_alter_offer_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='name_ua',
        ),
        migrations.AlterField(
            model_name='offersize',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offertype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.category', verbose_name='Категорія'),
            preserve_default=False,
        ),
    ]
