# Generated by Django 5.0.6 on 2024-05-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_category_catcodeepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catCodeEpicName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Epic Code Name'),
        ),
    ]
