# Generated by Django 5.0.4 on 2024-04-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_category_remove_offer_name_remove_offer_name_ua_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Категорії',
        ),
    ]
