# Generated by Django 5.0.6 on 2024-05-24 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_category_catcodeepicname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Main.category', verbose_name='Категорія'),
        ),
    ]
