# Generated by Django 5.0.4 on 2024-04-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='offersize',
            options={'verbose_name_plural': 'Розміри'},
        ),
        migrations.AlterModelOptions(
            name='offertype',
            options={'verbose_name_plural': 'Типи товарів'},
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
