# Generated by Django 5.0.4 on 2024-04-30 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_offercolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.offercolor', verbose_name='Колір'),
            preserve_default=False,
        ),
    ]
