# Generated by Django 5.0.4 on 2024-04-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_offer_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='article',
            field=models.CharField(default=1, max_length=100, verbose_name='Артикл'),
            preserve_default=False,
        ),
    ]
