# Generated by Django 5.0.4 on 2024-04-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_offer_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametr',
            fields=[
                ('parametr_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Параметр айді')),
                ('parametr_name', models.CharField(max_length=1000, verbose_name='Назва')),
                ('parametr_value', models.CharField(max_length=1000, verbose_name='Значення')),
            ],
            options={
                'verbose_name_plural': 'Параметри',
            },
        ),
        migrations.RemoveField(
            model_name='offer',
            name='size',
        ),
        migrations.AddField(
            model_name='offer',
            name='parameters',
            field=models.ManyToManyField(to='Main.parametr', verbose_name='Параметри'),
        ),
    ]
