# Generated by Django 5.0.4 on 2024-04-30 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_parametr_remove_offer_size_offer_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.offersize', verbose_name='Розмір товару'),
            preserve_default=False,
        ),
    ]
