# Generated by Django 5.0.4 on 2024-04-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_offer_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Офер айді')),
                ('image', models.CharField(max_length=1000, verbose_name='Зображення')),
            ],
            options={
                'verbose_name_plural': 'Зображення',
            },
        ),
        migrations.AlterField(
            model_name='offer',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL'), ('2XS', '2XS'), ('3XS', '3XS'), ('4XS', '4XS'), ('5XS', '5XS')], max_length=255, verbose_name='Розмір товару'),
        ),
        migrations.DeleteModel(
            name='OfferSize',
        ),
    ]
