# Generated by Django 5.0.4 on 2024-05-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_images_alter_offer_size_delete_offersize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Айді')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name_plural': 'Зображення',
            },
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='offer',
            name='desc',
            field=models.TextField(default=1, verbose_name='Опис російською'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='desc_ua',
            field=models.TextField(default=1, verbose_name='Опис українською'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Ціна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Кількість'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Айді'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='parametr_name',
            field=models.CharField(choices=[('Колір', 'Color'), ('Розмір', 'Size'), ('Артикл', 'Article'), ('Матеріал', 'Material'), ('Країна виробника', 'Country of production'), ('Призначення', 'Description'), ('Стиль', 'Style')], max_length=1000, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='offer',
            name='images',
            field=models.ManyToManyField(to='Main.image', verbose_name='Зображення'),
        ),
    ]
