# Generated by Django 5.0.4 on 2024-05-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_image_delete_images_offer_desc_offer_desc_ua_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
