# Generated by Django 5.0.4 on 2024-05-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_alter_offer_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametr',
            name='parametr_name',
            field=models.CharField(choices=[('Color', 'Цвет'), ('Size', 'Розмір'), ('Article', 'Артикл'), ('Material', 'Матеріал'), ('Country of production', 'Країна виробника'), ('Description', 'Опис російською')], max_length=1000, verbose_name='Назва'),
        ),
    ]
