# Generated by Django 5.0.4 on 2024-05-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_alter_parametr_parametr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='parameters',
            field=models.ManyToManyField(blank=True, null=True, to='Main.parametr', verbose_name='Параметри'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='parametr_name',
            field=models.CharField(choices=[('Color', 'Цвет'), ('Size', 'Размер'), ('Article', 'Артикл'), ('Material', 'Матеріал'), ('Country of production', 'Країна виробника'), ('Description', 'Опис російською')], max_length=1000, verbose_name='Назва'),
        ),
    ]
