# Generated by Django 5.0.4 on 2024-05-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_alter_offer_parameters_alter_parametr_parametr_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(primary_key=True, serialize=False, verbose_name='URL'),
        ),
    ]
