# Generated by Django 5.0.4 on 2024-05-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_image_id_alter_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
