# Generated by Django 5.0.4 on 2024-05-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_alter_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(primary_key=True, serialize=False, unique=True, verbose_name='URL'),
        ),
    ]
