# Generated by Django 5.0.4 on 2024-05-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_remove_image_id_alter_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='URL'),
        ),
    ]
