# Generated by Django 5.0.4 on 2024-05-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_alter_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
