# Generated by Django 5.0.4 on 2024-05-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_image_id_alter_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='Main.image', verbose_name='Зображення'),
        ),
    ]
