# Generated by Django 5.0.4 on 2024-05-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_alter_offer_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='images',
            field=models.ManyToManyField(to='Main.image', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='parameters',
            field=models.ManyToManyField(to='Main.parametr', verbose_name='Параметри'),
        ),
    ]
